#!/bin/bash

cd /home/kgotfryd/programming/workspace/buildroot-2017.02.10/
cd output/target/etc/init.d
touch S70nfs_mount
echo "!#/bin/sh" > S70nfs_mount
echo "mkdir /root/linux" >> S70nfs_mount
echo "mount 192.168.1.3:/exports/workspace/linux_qemu /root/linux -v -o nfsvers=3,vers=3" >> S70nfs_mount
chmod a+x S70nfs_mount
