#!/bin/bash
#qemu-system-x86_64 -M pc -kernel /home/kgotfryd/programming/workspace/buildroot-2017.02.10/output/images/bzImage -drive file=/home/kgotfryd/programming/workspace/buildroot-2017.02.10/output/images/rootfs.ext2,if=virtio,format=raw -append root=/dev/vda -net nic,model=virtio -net user -smp 4 

DIR_PREFIX=/home/kgotfryd/programming/workspace
#KERNEL_PATH=$DIR_PREFIX/buildroot-2017.02.10/output/images/bzImage
KERNEL_PATH=$DIR_PREFIX/linux_qemu/arch/x86_64/boot/bzImage
ROOTFS_PATH=$DIR_PREFIX/buildroot-2017.02.10/output/images/rootfs.ext2

qemu-system-x86_64 -M pc -kernel $KERNEL_PATH -drive file=$ROOTFS_PATH,if=virtio,format=raw -append root=/dev/vda -net nic,model=virtio -net user -smp 4 -s
